<?php
// Standard OpenEMR initialization
require_once("../../globals.php");
require_once("$srcdir/api.inc");

// Securely get PID and Encounter ID
$pid = intval($_GET['pid']);
$encounter = intval($_GET['encounter']);

// Fetch Patient Information
$patient = sqlQuery("SELECT fname, lname, DOB FROM patient_data WHERE pid = ?", array($pid));

// Fetch Encounter Date
$encounter_data = sqlQuery("SELECT date FROM form_encounter WHERE pid = ? AND encounter = ?", array($pid, $encounter));

// Fetch CAMOS Data
$camos = sqlQuery("SELECT * FROM form_CAMOS WHERE pid = ? AND encounter = ?", array($pid, $encounter));

// Begin HTML Output
?>
<!DOCTYPE html>
<html>
<head>
    <title>Print CAMOS Note</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            margin: 40px;
            color: #333;
        }
        .header, .footer {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 24px;
            margin: 0;
        }
        .patient-info {
            margin-bottom: 20px;
            font-size: 16px;
        }
        .content {
            border: 1px solid #ccc;
            padding: 20px;
            background-color: #f9f9f9;
            font-size: 16px;
            line-height: 1.6;
            min-height: 300px;
        }
        .signature {
            margin-top: 50px;
        }
        .signature-line {
            margin-top: 40px;
            border-top: 1px solid #000;
            width: 300px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 5px;
            text-align: center;
        }
        @media print {
            .no-print {
                display: none;
            }
        }
        button {
            margin-bottom: 20px;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
        }
    </style>
</head>
<body>

<div class="no-print">
    <button onclick="window.print();">Print This CAMOS Entry</button>
</div>

<div class="header">
    <h1>Medical Record - CAMOS Note</h1>
</div>

<div class="patient-info">
    <strong>Patient Name:</strong> <?php echo htmlspecialchars($patient['fname'] . ' ' . $patient['lname']); ?><br>
    <strong>Date of Birth:</strong> <?php echo htmlspecialchars(oeFormatShortDate($patient['DOB'])); ?><br>
    <strong>Encounter Date:</strong> <?php echo htmlspecialchars(oeFormatShortDate($encounter_data['date'])); ?><br>
</div>

<div class="content">
    <?php echo nl2br(htmlspecialchars($camos['data'])); ?>
</div>

<div class="signature">
    <div class="signature-line">
        Physician Signature
    </div>
</div>

<div class="footer">
    Generated by OpenEMR - <?php echo date('F j, Y'); ?>
</div>

</body>
</html>
